# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
